export const queryData = [
  {
    id: 1,
    date: "15/Jun/2025",
    chosen: "Light",
    plate: "XYZ1234",
    status: "Success",
    purchase: "Access your report",
  },
  {
    id: 2,
    date: "22/May/2025",
    chosen: "Ultra",
    plate: "ABC5678",
    status: "Paid",
    purchase: "Access your report",
  },
  {
    id: 3,
    date: "10/Apr/2025",
    chosen: "Plus",
    plate: "DEF9012",
    status: "Success",
    purchase: "Access your report",
  },
  {
    id: 4,
    date: "28/Mar/2025",
    chosen: "Placa Protegida",
    plate: "GHI3456",
    status: "Reprocessing",
    purchase: "Access your report",
  },
  {
    id: 5,
    date: "14/Feb/2025",
    chosen: "Light",
    plate: "JKL7890",
    status: "Open",
    purchase: "Access your report",
  },
  {
    id: 6,
    date: "30/Jan/2025",
    chosen: "Ultra",
    plate: "MNO1234",
    status: "Paid",
    purchase: "Access your report",
  },
  {
    id: 7,
    date: "18/Dec/2024",
    chosen: "Plus",
    plate: "PQR5678",
    status: "Success",
    purchase: "Access your report",
  },
  {
    id: 8,
    date: "05/Nov/2024",
    chosen: "Placa Protegida",
    plate: "STU9012",
    status: "Partial",
    purchase: "Access your report",
  },
  {
    id: 9,
    date: "21/Oct/2024",
    chosen: "Light",
    plate: "VWX3456",
    status: "Success",
    purchase: "Access your report",
  },
  {
    id: 10,
    date: "08/Sep/2024",
    chosen: "Ultra",
    plate: "YZA7890",
    status: "Paid",
    purchase: "Access your report",
  },
  {
    id: 11,
    date: "15/Jun/2025",
    chosen: "Light",
    plate: "ZZZ1234",
    status: "Success",
    purchase: "Access your report",
  },
  {
    id: 12,
    date: "22/May/2025",
    chosen: "Ultra",
    plate: "AAA5678",
    status: "Paid",
    purchase: "Access your report",
  },
  {
    id: 13,
    date: "10/Apr/2025",
    chosen: "Plus",
    plate: "BBB9012",
    status: "Success",
    purchase: "Access your report",
  },
  {
    id: 14,
    date: "28/Mar/2025",
    chosen: "Placa Protegida",
    plate: "CCC3456",
    status: "Reprocessing",
    purchase: "Access your report",
  },
  {
    id: 15,
    date: "14/Feb/2025",
    chosen: "Light",
    plate: "DDD7890",
    status: "Open",
    purchase: "Access your report",
  },
  {
    id: 16,
    date: "30/Jan/2025",
    chosen: "Ultra",
    plate: "EEE1234",
    status: "Paid",
    purchase: "Access your report",
  },
  {
    id: 17,
    date: "18/Dec/2024",
    chosen: "Plus",
    plate: "FFF5678",
    status: "Success",
    purchase: "Access your report",
  },
  {
    id: 18,
    date: "05/Nov/2024",
    chosen: "Placa Protegida",
    plate: "GGG9012",
    status: "Partial",
    purchase: "Access your report",
  },
  {
    id: 19,
    date: "21/Oct/2024",
    chosen: "Light",
    plate: "HHH3456",
    status: "Success",
    purchase: "Access your report",
  },
  {
    id: 20,
    date: "08/Sep/2024",
    chosen: "Ultra",
    plate: "III7890",
    status: "Paid",
    purchase: "Access your report",
  },
];
