const singlePlans = [
  {
    id: 1,
    name: "Relatório Premium",
    price: "R$ 58,00",
    desc: "Consulta única",
    features: [
      "Everything from the previous plan",
      "Renajud",
      "Renainf",
      "Histórico de relatórios",
      "Rental Empresa registration",
      "Complete Technical Sheet and much more",
    ],
  },
  {
    id: 2,
    name: "Relatório Ultra",
    price: "R$ 44,90",
    desc: "Complete consultation",
    features: [
      "Everything from the previous plan",
      "Ownership history",
      "Inspection checklist",
      "Fipe and Price Chart",
      "Lien",
      "Recall and much more...",
    ],
  },
  {
    id: 3,
    name: "Plus Plan",
    price: "R$ 55,90",
    desc: "Multi consultation",
    features: [
      "Everything from the previous plan",
      "State restrictions",
      "National restrictions",
      "Débitos e Multas",
      "Fipe Table",
      "Chassis Decoder",
    ],
  },
  {
    id: 4,
    name: "Relatório Light",
    price: "R$ 27,90",
    desc: "Unlimited consultation",
    features: [
      "Vehicle Registration Data",
      "*Histórico de KM",
      "Market price",
      "Loss Index",
    ],
  },
];

const multiPlans = [
  {
    id: 5,
    name: "Sempre Presente",
    planNumber: "Pacote R$ 1.200,00",
    priceDesc: "Compre R$ 1.200,00 e pague",
    price: "R$900.00",
    discount: "-25%",
    desc: "de economia",
  },
  {
    id: 6,
    name: "Olho na segurança",
    planNumber: "Pacote R$ 700,00",
    priceDesc: "Buy R$ 700,00 and pay",
    price: "R$500.00",
    discount: "-21%",
    desc: "de economia",
  },
  {
    id: 7,
    name: "Profissional",
    planNumber: "Pacote R$ 500,00",
    priceDesc: "Compre R$ 500,00 e pague",
    price: "R$410.00",
    discount: "-18%",
    desc: "de economia",
  },
  {
    id: 8,
    name: "Negociador",
    planNumber: "Pacote R$ 300,00",
    priceDesc: "Compre R$ 300,00 e pague",
    price: "R$250.00",
    discount: "-17%",
    desc: "de economia",
  },
  {
    id: 9,
    name: "Test Drive",
    planNumber: "Pacote R$ 150,00",
    priceDesc: "Compre R$ 150,00 e pague",
    price: "R$140.00",
    discount: "-7%",
  },
];

export { singlePlans, multiPlans };
